matrix:
  include:
    - language: rust
      os: linux
        dist: xenial
      addons:
        apt:
          sources:
            sourceline: 'deb http://ftp.us.debian.org/debian unstable main contrib'
            key_url: 'https://ftp-master.debian.org/keys/archive-key-10.asc'
          packages:
            - libwebkit2gtk-4.0-dev
            - build-essential
            - curl
            - libssl-dev
            - libgtk-3-dev
            - appmenu-gtk3-module
      rust:
        - stable
        - beta
        - nightly
      cache:
        cargo: true
        apt: true
      before_script:
        - cd src-tauri
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
    - language: rust
      os: windows
      before_script:
        - cargo install tauri-bundler --force
      rust:
        - stable
        - beta
        - nightly
      cache:
        cargo: true
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
    - language: rust
      os: osx
      addons:
        homebrew:
          packages:
            - gcc
      before_script:
        - cargo install tauri-bundler --force
      rust:
        - stable
        - beta
        - nightly
      cache:
        cargo: true
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
    - language: node_js
      node_js:
        - stable
      install:
        - yarn
      cache:
        yarn: true
      script:
        - yarn install
        - yarn test
        - yarn prod
