matrix:
        include:
                - language: rust
                  addons:
                          apt:
                                  sources:
                                          sourceline: "deb http://ftp.us.debian.org/debian main contrib"
                                          key_url: "https://ftp-master.debian.org/keys/archive-key-10.asc"
                                  update: true
                                  packages:
                                          - libwebkit2gtk-4.0-dev 
                                          - build-essential 
                                          - curl 
                                          - libssl-dev 
                                          - libgtk-3-dev
                                          - appmenu-gtk3-module 
                  rust:
                          - stable

                  cache: cargo
                  before_script:
                          - cd src-tauri
                  script:
                          - cargo test
                          - cargo build

                - language: node_js
                  node_js:
                          - "stable"
                  install:
                          - yarn
                  cache:
                          - yarn
                  script:
                          - yarn install
                          - yarn test
                          - yarn prod
