set dotenv-load

build:
    GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags lambda.norpc -ldflags "-X main.stripeSecretKey=$STRIPE_SECRET_KEY" -o bootstrap cancel_payment_intent.go
    zip bootstrap.zip bootstrap
    rm bootstrap
