-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ZeitplanApi.Object exposing (..)


type Calendar
    = Calendar


type Event
    = Event


type Meeting
    = Meeting


type PaymentIntent
    = PaymentIntent


type PaymentUpdate
    = PaymentUpdate


type ScheduleMeetingResult
    = ScheduleMeetingResult


type ScheduleResponse
    = ScheduleResponse


type Schedules
    = Schedules


type StatusResponse
    = StatusResponse


type User
    = User
