-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ZeitplanApi.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import ZeitplanApi.Scalar exposing (defaultCodecs)


type alias Id =
    ZeitplanApi.Scalar.Id


type alias Long =
    ZeitplanApi.Scalar.Long


codecs : ZeitplanApi.Scalar.Codecs Id Long
codecs =
    ZeitplanApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecLong = defaultCodecs.codecLong
        }
