set dotenv-load

build:
    GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags lambda.norpc -ldflags "-X main.cognitoClientId=$LAMBDA_COGNITO_CLIENT -X main.cognitoClientSecret=$LAMBDA_COGNITO_SECRET" -o bootstrap user_db_stream.go
    zip bootstrap.zip bootstrap
    rm bootstrap
