-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLApi.Object.Meeting exposing (..)

import GraphQLApi.InputObject
import GraphQLApi.Interface
import GraphQLApi.Object
import GraphQLApi.Scalar
import GraphQLApi.ScalarCodecs
import GraphQLApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


participants : SelectionSet (List GraphQLApi.ScalarCodecs.Id) GraphQLApi.Object.Meeting
participants =
    Object.selectionForField "(List ScalarCodecs.Id)" "participants" [] (GraphQLApi.ScalarCodecs.codecs |> GraphQLApi.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.list)


title : SelectionSet String GraphQLApi.Object.Meeting
title =
    Object.selectionForField "String" "title" [] Decode.string


duration : SelectionSet Int GraphQLApi.Object.Meeting
duration =
    Object.selectionForField "Int" "duration" [] Decode.int


created : SelectionSet GraphQLApi.ScalarCodecs.Long GraphQLApi.Object.Meeting
created =
    Object.selectionForField "ScalarCodecs.Long" "created" [] (GraphQLApi.ScalarCodecs.codecs |> GraphQLApi.Scalar.unwrapCodecs |> .codecLong |> .decoder)
