set dotenv-load

build:
    GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags lambda.norpc -ldflags "-X main.stripeSecretKey=$STRIPE_SECRET_KEY -X main.endpointSecret=$STRIPE_WEBHOOK_SECRET" -o bootstrap stripe_webhook.go
    zip bootstrap.zip bootstrap
    rm bootstrap
