set dotenv-load

build-stripe-checkout:
    just lambdas/create_payment_intent/build
    
build-create-user:
    just lambdas/create_user/build
    
build-stripe-webhook:
    just lambdas/stripe_webhook/build
    
build: build-stripe-checkout build-create-user build-stripe-webhook
