set dotenv-load

build-stripe-checkout:
    just lambdas/create_payment_intent/build
    
build-create-user:
    just lambdas/create_user/build
    
build-stripe-webhook:
    just lambdas/stripe_webhook/build
    
build-user-db-stream:
    just lambdas/user_db_stream/build
    
deploy:
    cdk deploy --outputs-file ../web/aws-cdk-outputs.json
    
build: build-stripe-checkout build-create-user build-stripe-webhook build-user-db-stream
