-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ZeitplanApi.Object.ScheduleResponse exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ZeitplanApi.InputObject
import ZeitplanApi.Interface
import ZeitplanApi.Object
import ZeitplanApi.Scalar
import ZeitplanApi.ScalarCodecs
import ZeitplanApi.Union


schedule :
    SelectionSet decodesTo ZeitplanApi.Object.ScheduleMeetingResult
    -> SelectionSet (Maybe (List decodesTo)) ZeitplanApi.Object.ScheduleResponse
schedule object____ =
    Object.selectionForCompositeField "schedule" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


failed : SelectionSet (Maybe (List String)) ZeitplanApi.Object.ScheduleResponse
failed =
    Object.selectionForField "(Maybe (List String))" "failed" [] (Decode.string |> Decode.list |> Decode.nullable)


error : SelectionSet (Maybe String) ZeitplanApi.Object.ScheduleResponse
error =
    Object.selectionForField "(Maybe String)" "error" [] (Decode.string |> Decode.nullable)
