-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLApi.Mutation exposing (..)

import GraphQLApi.InputObject
import GraphQLApi.Interface
import GraphQLApi.Object
import GraphQLApi.Scalar
import GraphQLApi.ScalarCodecs
import GraphQLApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias SaveCalendarOptionalArguments =
    { name : OptionalArgument String }


type alias SaveCalendarRequiredArguments =
    { events : List GraphQLApi.InputObject.EventInput }


saveCalendar :
    (SaveCalendarOptionalArguments -> SaveCalendarOptionalArguments)
    -> SaveCalendarRequiredArguments
    -> SelectionSet decodesTo GraphQLApi.Object.Calendar
    -> SelectionSet decodesTo RootMutation
saveCalendar fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { name = Absent }

        optionalArgs____ =
            [ Argument.optional "name" filledInOptionals____.name Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "saveCalendar" (optionalArgs____ ++ [ Argument.required "events" requiredArgs____.events (GraphQLApi.InputObject.encodeEventInput |> Encode.list) ]) object____ Basics.identity


type alias SaveMeetingOptionalArguments =
    { created : OptionalArgument GraphQLApi.ScalarCodecs.Long }


type alias SaveMeetingRequiredArguments =
    { participants : List GraphQLApi.ScalarCodecs.Id
    , title : String
    , duration : Int
    }


saveMeeting :
    (SaveMeetingOptionalArguments -> SaveMeetingOptionalArguments)
    -> SaveMeetingRequiredArguments
    -> SelectionSet decodesTo GraphQLApi.Object.Meeting
    -> SelectionSet decodesTo RootMutation
saveMeeting fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { created = Absent }

        optionalArgs____ =
            [ Argument.optional "created" filledInOptionals____.created (GraphQLApi.ScalarCodecs.codecs |> GraphQLApi.Scalar.unwrapEncoder .codecLong) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "saveMeeting" (optionalArgs____ ++ [ Argument.required "participants" requiredArgs____.participants ((GraphQLApi.ScalarCodecs.codecs |> GraphQLApi.Scalar.unwrapEncoder .codecId) |> Encode.list), Argument.required "title" requiredArgs____.title Encode.string, Argument.required "duration" requiredArgs____.duration Encode.int ]) object____ Basics.identity


type alias SaveEventsRequiredArguments =
    { events : List GraphQLApi.InputObject.EventInput }


saveEvents :
    SaveEventsRequiredArguments
    -> SelectionSet decodesTo GraphQLApi.Object.Event
    -> SelectionSet (List decodesTo) RootMutation
saveEvents requiredArgs____ object____ =
    Object.selectionForCompositeField "saveEvents" [ Argument.required "events" requiredArgs____.events (GraphQLApi.InputObject.encodeEventInput |> Encode.list) ] object____ (Basics.identity >> Decode.list)
