-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLApi.Object exposing (..)


type Calendar
    = Calendar


type Event
    = Event


type Meeting
    = Meeting


type PaymentIntent
    = PaymentIntent


type User
    = User
