-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GraphQLApi.ScalarCodecs exposing (..)

import GraphQLApi.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    GraphQLApi.Scalar.Id


type alias Long =
    GraphQLApi.Scalar.Long


codecs : GraphQLApi.Scalar.Codecs Id Long
codecs =
    GraphQLApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecLong = defaultCodecs.codecLong
        }
